# Generated by Django 3.0.5 on 2020-04-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='48px * 48px의 이미지를 업로드 해주세요', upload_to='accounts/avatar/%Y/%m/%d'),
        ),
    ]
